title: Statically
slogan: A free multi-CDN for open source project, WordPress, images and more!
description: Statically is a free multi-CDN for open source project, WordPress, images and other assets with high-performance of caching and optimization.
baseurl: 'https://statically.io'

language: en
charset: utf-8
version: 2.0.0

defaults: []