title: 'Statically'
slogan: 'A free multi-CDN for open source project, WordPress, images and more!'
description: 'Statically is a free multi-CDN for open source project, WordPress, images and other assets with high-performance of caching and optimization.'
permalink: /:title/
url: 'http://127.0.0.1/statically/_site' # 'https://statically.io'

language: en
direction: ltr
charset: utf-8
version: 2.0.0

data_centers:
  - Cloudflare
  - Fastly
  - CDN77
  - BunnyCDN

# Default field values for pages
defaults:
  -
    scope:
      path: ""
    values:
      title: 'Page Title'
      description: 'Page description.'
      layout: page
      layout_data:
        animation: true
        skin:
          # [background-color, color]
          body: ['#1a252f', '#fff']
          # [a, a:hover, a:active]
          a: ['rgba(255, 255, 255, .6)', 'rgba(255, 255, 255, .8)']
          # [button, button:hover, button:active]
          button: ['rgba(255, 255, 255, .1)', 'rgba(255, 255, 255, .15)', 'rgba(255, 255, 255, .12)']

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-minifier

# Plugin settings
kramdown:
  input: GFM
  hard_wrap: false
jekyll-minifier:
  uglifier_args:
    harmony: true

# Include to public directory
include:
  - '_headers'
  - '_redirects'